# Generated by Django 5.2.1 on 2025-09-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics/"),
        ),
    ]
