# Generated by Django 5.2.1 on 2025-09-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_remove_profile_profile_image_profile_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(default="default.png", upload_to="profiles/"),
        ),
    ]
